version: "3"
services:
  home:
    build:
      context: home/
      dockerfile: Dockerfile
    ports:
      - "7300:80"
  ai-learning:
    build:
      context: ai-learning/
      dockerfile: Dockerfile
    ports:
      - "7301:80"
